name: manhattan_env
channels:
  - conda-forge
  - defaults
dependencies:
  - r-base=4.3.0 # Using R version 4.3.0 as requested
  - r-optparse
  - r-data.table
  - r-tidyverse
  - r-ggrepel
  - r-dplyr # Although part of tidyverse, explicitly adding for clarity
  - r-ggplot2 # Although part of tidyverse, explicitly adding for clarity
